import SwiftUI
import Combine

class LanguageManager: ObservableObject {
    static let shared = LanguageManager()
    
    @AppStorage("pref_language") var languageCode: String = "tr" {
        didSet {
            // Notify SwiftUI views to update
            objectWillChange.send()
        }
    }
    
    func translate(_ key: String) -> String {
        if languageCode == "en" {
            return translations[key] ?? key
        }
        return key
    }
    
    // Translation dictionary for Turkish keys to English values (deduplicated)
    private let translations: [String: String] = [
        // Tab / Navigation / Section Titles
        "Tercihler": "Preferences",
        "Profil": "Profile",
        "Hesap Bilgileri": "Account Info",
        "Kişisel Bilgiler": "Personal Info",
        "Bilgilerinizi ve şifrenizi güncelleyin": "Update your info & password",
        "Adreslerim": "My Addresses",
        "Kayıtlı teslimat adresleri": "Saved delivery addresses",
        "Ödeme Yöntemleri": "Payment Methods",
        "Kayıtlı kredi kartları ve cüzdan": "Saved cards and wallet",
        "Ayarlar ve Tercihler": "Settings & Preferences",
        "Bildirim, tema ve dil ayarları": "Notification, theme and language settings",
        "Yardım ve Destek": "Help & Support",
        "Sıkça sorulan sorular ve destek talepleri": "FAQs and support tickets",
        "Çıkış Yap": "Log Out",
        "Oturumu sonlandır": "End session",
        "TERCİHLER": "PREFERENCES",
        "GÜVENLİK": "SECURITY",
        "Giriş Yap": "Log In",
        "Kayıt Ol": "Sign Up",
        "Favorilerim": "My Favorites",
        "Şifre Değiştir": "Change Password",
        "Telefon Doğrulama": "Phone Verification",
        "E-posta Doğrulama": "Email Verification",
        "Kullanıcı Bilgileri": "User Information",
        "Ödeme Yöntemlerim": "My Payment Methods",
        "Kayıtlı kartlarınız ve Apple Pay": "Saved cards & Apple Pay",
        "Geçmiş ve Favoriler": "History & Favorites",
        "Geçmiş siparişleriniz ve favori ustalar": "Your past orders and favorite experts",
        "Yardım": "Help",
        "Destek": "Support",
        "Yardım merkezi ve müşteri hizmetleri": "Help center & customer service",
        "Destek ve Yardım Ekranı": "Support & Help Screen",
        
        // Preferences Page / View
        "BİLDİRİM AYARLARI": "NOTIFICATION SETTINGS",
        "Bildirim Ayarları": "Notification Settings",
        "Anlık Bildirimler (Push)": "Push Notifications",
        "E-posta Bildirimleri": "Email Notifications",
        "SMS Bildirimleri": "SMS Notifications",
        "Rezervasyon Güncellemeleri": "Booking Updates",
        "Kampanya ve Tanıtımlar": "Campaigns & Promos",
        "Sistem ve Güvenlik": "System & Security",
        "Rezervasyon": "Bookings",
        "Kampanya & Promosyon": "Campaigns & Promos",
        "Sistem Bildirimleri": "System Notifications",
        "Bildirim izni reddedilmiş.": "Notification permission denied.",
        "Bildirim Türleri": "Notification Types",
        "Profilim Herkese Açık": "My Profile is Public",
        "Veri Toplama Onayı": "Data Collection Consent",
        "GÖRÜNÜM AYARLARI": "APPEARANCE SETTINGS",
        "Görünüm Ayarları": "Appearance Settings",
        "Tema": "Theme",
        "Sistem": "System",
        "Açık": "Light",
        "Koyu": "Dark",
        "DİL SEÇİMİ": "LANGUAGE SELECTION",
        "Dil Ayarları": "Language Settings",
        "Uygulama Dili": "App Language",
        "Tema Seçimi": "Theme Selection",
        "Dil": "Language",
        "GİZLİLİK AYARLARI": "PRIVACY SETTINGS",
        "Gizlilik Ayarları": "Privacy Settings",
        "Konum Paylaşımı": "Location Sharing",
        "Profil Görünürlüğü (Herkese Açık)": "Profile Visibility (Public)",
        "Kullanım Verisi Analiz İzni": "Data Collection Analytics",
        "Tüm tercihler otomatik olarak kaydedilir.": "All preferences are automatically saved.",
        "Tercihler kaydedildi!": "Preferences saved!",
        "Ayarları Kaydet": "Save Settings",
        
        // General UI & Loadings
        "Profil yükleniyor...": "Loading profile...",
        "Tercihleriniz yükleniyor...": "Loading preferences...",
        "Hata Oluştu": "Error Occurred",
        "Bir Hata Oluştu": "An Error Occurred",
        "Tekrar Dene": "Retry",
        "Kapat": "Close",
        
        // Homepage & History
        "Hoş Geldiniz": "Welcome",
        "Uzman Bul": "Find an Expert",
        "Ara": "Search",
        "Kategoriler": "Categories",
        "Popüler Hizmetler": "Popular Services",
        "Tümünü Gör": "See All",
        "Geçmiş": "Past",
        "Favoriler": "Favorites",
        "Verileriniz yükleniyor...": "Loading your data...",
        "Kartlarınız yükleniyor...": "Loading your cards...",
        "Adresleriniz yükleniyor...": "Loading your addresses...",
        "Henüz rezervasyon bulunmuyor.": "No bookings found yet.",
        "Favori uzmanınız bulunmuyor.": "No favorite experts found.",
        
        // Edit Profile Page & SMS / Crop
        "Fotoğrafı Değiştir": "Change Photo",
        "Ad Soyad": "Full Name",
        "E-posta": "Email",
        "E-posta değişikliği doğrulama maili gerektirir.": "Email change requires a validation email.",
        "Telefon Numarası": "Phone Number",
        "Doğrula": "Verify",
        "Değişiklikleri Kaydet": "Save Changes",
        "Mevcut Şifre": "Current Password",
        "Yeni Şifre": "New Password",
        "Yeni Şifre (Tekrar)": "Confirm New Password",
        "Şifre Gücü: ": "Password Strength: ",
        "Çok Zayıf": "Very Weak",
        "Zayıf": "Weak",
        "Orta": "Medium",
        "Güçlü": "Strong",
        "Çok Güçlü": "Very Strong",
        "Şifreyi Güncelle": "Update Password",
        "Bilgileri Düzenle": "Edit Profile",
        "SMS Doğrulama": "SMS Verification",
        "%@ numaralı telefona gönderilen 4 haneli doğrulama kodunu girin.\n(Mock Kodu: 1234)": "Enter the 4-digit verification code sent to %@.\n(Mock Code: 1234)",
        "Doğrulama Kodu": "Verification Code",
        "Onayla ve Telefonu Güncelle": "Confirm & Update Phone",
        "Doğrulama": "Verification",
        "Görseli Kırp / Ölçeklendir": "Crop / Scale Image",
        "Ölçek: %%%d": "Scale: %%%d",
        "Kırp ve Uygula": "Crop & Apply",
        "Kırpma": "Cropping",
        "Profil bilgileriniz başarıyla güncellendi.": "Your profile info has been successfully updated.",
        "Yeni şifreler eşleşmiyor.": "New passwords do not match.",
        "Şifreniz başarıyla değiştirildi.": "Your password has been successfully changed.",
        "Telefon numaranız doğrulandı.": "Your phone number has been verified.",
        
        // Homepage & Login & Logout & Categories
        "Konumunuz": "Your Location",
        "Hizmet, uzman veya kategori ara…": "Search services, experts or categories...",
        "Hizmet, uzman veya kategori ara...": "Search services, experts or categories...",
        "(0 yorum)": "(0 reviews)",
        "başlangıç fiyatı": "starting price",
        "Hoşgeldiniz": "Welcome",
        "Beni Hatırla": "Remember Me",
        "Şifremi Unuttum": "Forgot Password",
        "GİRİŞ YAP": "LOG IN",
        "VEYA": "OR",
        "Hesabın yok mu?": "Don't have an account?",
        "Uzman mısın?": "Are you an expert?",
        "Başvuru Yap": "Apply Now",
        "Hesabınızdan çıkmak istediğinizden emin misiniz?": "Are you sure you want to log out of your account?",
        "İptal": "Cancel",
        "su tesisatı": "plumbing",
        "Kombi & Klima Bakımı": "Boiler & AC Maintenance",
        "Yazılım & Teknoloji": "Software & Tech",
        "Boya & Badana": "Painting & Whitewash",
        "Su tesisatı bakım": "Plumbing maintenance",
        "Yıllık bakım": "Annual maintenance",
        "Mobil uygulama (iOS)": "Mobile app (iOS)",
        "Profesyonel Boya": "Professional Painting",
        
        // Side Menu & Customer Profile View
        "Ana Sayfa": "Home",
        "Profilim": "My Profile",
        "Mesajlar": "Messages",
        "Ayarlar": "Settings",
        "Kullanıcı": "User",
        "Yeni Üye": "New Member",
        "%d Ay Üye": "%d Months Member",
        "%d Yıl Üye": "%d Years Member",
        "Siparişlerim": "My Orders",
        "İLETİŞİM BİLGİLERİ": "CONTACT INFO",
        "Telefon": "Phone",
        "DOĞRULANDI": "VERIFIED",
        "DOĞRULA": "VERIFY",
        "HESAP AYARLARI": "ACCOUNT SETTINGS",
        "GEÇMİŞ & FAVORİLER": "HISTORY & FAVORITES",
        "Düzenle": "Edit",
        
        // Filter Sheet
        "Kategori": "Category",
        "Tüm Kategoriler": "All Categories",
        "Şehir": "City",
        "Tüm Şehirler": "All Cities",
        "Fiyat Aralığı": "Price Range",
        "Sıralama": "Sort By",
        "Varsayılan": "Default",
        "Fiyat: Düşükten Yükseğe": "Price: Low to High",
        "Fiyat: Yüksekten Düşüğe": "Price: High to Low",
        "Sıfırla": "Reset",
        "Uygula": "Apply",
        "Filtrele & Sırala": "Filter & Sort",
        "Filtre aktif": "Filter active",
        "Temizle": "Clear",
        
        // Messages Page & Settings Page
        "Henüz mesaj bulunmuyor.": "No messages found yet.",
        "Uygulama": "App",
        "Bildirimler": "Notifications",
        "KVKK ve Gizlilik": "KVKK & Privacy",
        "Hakkında": "About",
        
        // User Info Edit View
        "Ad": "First Name",
        "Soyad": "Last Name",
        "Doğrulandı": "Verified",
        "SMS ile Doğrula": "Verify with SMS",
        "Hesap şifreni güvenli şekilde güncelle": "Update your account password securely",
        "DEĞİŞİKLİKLERİ KAYDET": "SAVE CHANGES",
        
        // Order History & Favorites additions
        "Sipariş Geçmişim": "My Order History",
        "Sipariş Geçmişi": "Order History",
        "Tümü": "All",
        "Tamamlandı": "Completed",
        "İptal Edildi": "Cancelled",
        "Bekliyor": "Pending",
        "Değerlendir": "Rate",
        "Tekrarla": "Repeat",
        "Sipariş geçmişi bulunamadı": "No order history found",
        "Tamamlanan siparişleriniz burada görünecek.": "Your completed orders will appear here.",
        "Favorin yok": "No favorites",
        "Ana sayfadan kalp ikonuna basarak favori ekleyebilirsin.": "You can add favorites by tapping the heart icon on the homepage.",
        "Hata": "Error",
        "Tamam": "OK",
        "Bilinmeyen hata": "Unknown error",
        "Henüz favori yok": "No favorites yet",
        "Beğendiğiniz uzmanları favorilere ekleyin.": "Add the experts you like to your favorites.",
        "İletişim": "Contact",
        "Rezervasyonlarım": "My Bookings",
        
        // Reservation Statuses
        "Beklemede": "Pending",
        "Onaylandı": "Approved",
        "Reddedildi": "Rejected",

        // Reservation Detail & Sheets
        "Randevu Bilgileri": "Appointment Details",
        "Randevu Tarihi": "Appointment Date",
        "Not ekle": "Add a note",
        "Not": "Note",
        "Not eklenmemiş.": "No note added.",
        "Rezervasyon Talebi Oluştur": "Create Reservation Request",
        "Rezervasyon Detayı": "Reservation Detail",
        "İşlemler": "Actions",
        "Mesaj Gönder": "Send Message",
        "Rezervasyonu reddet": "Reject reservation",
        "Bu rezervasyonu reddetmek istediğinizden emin misiniz?": "Are you sure you want to reject this reservation?",
        "%@ adlı müşterinin rezervasyon talebini reddetmek istediğinizden emin misiniz?": "Are you sure you want to reject the reservation request of customer %@?",
        "Rezervasyonu iptal et": "Cancel reservation",
        "Bu rezervasyonu iptal etmek istediğinizden emin misiniz?": "Are you sure you want to cancel this reservation?",
        "Oturum açmış kullanıcı bulunamadı.": "Active session user not found.",
        "Bu rezervasyon için mesajlaşma yetkiniz yok.": "You do not have messaging permission for this reservation.",
        "Bu rezervasyon için karar verme yetkiniz yok.": "You do not have decision-making permission for this reservation.",
        "Bu rezervasyonu iptal edemezsiniz.": "You cannot cancel this reservation.",
        "Rezervasyon talebiniz oluşturuldu.": "Your reservation request has been created.",
        "Gelen Rezervasyonlar": "Incoming Reservations",
        "Bekleyen": "Pending",
        "Bugün": "Today",
        "Yaklaşan": "Upcoming",
        "Rezervasyonlar yükleniyor...": "Loading reservations...",
        "Rezervasyon filtresi": "Reservation filter",
        "Bekleyen rezervasyon yok": "No pending reservations",
        "Bugün için rezervasyon yok": "No reservations for today",
        "Yaklaşan rezervasyon yok": "No upcoming reservations",
        "Geçmiş rezervasyon yok": "No past reservations",
        "Müşterilerden gelen yeni rezervasyon talepleri burada görünür.": "New reservation requests from customers will appear here.",
        "Bugünkü aktif rezervasyonlar burada görünür.": "Active reservations for today will appear here.",
        "Bugünden sonraki aktif rezervasyonlar burada görünür.": "Active reservations after today will appear here.",
        "Tamamlanan, reddedilen veya iptal edilen rezervasyonlar burada görünür.": "Completed, rejected, or cancelled reservations will appear here.",
        "Kabul Et": "Accept",
        "Reddet": "Reject",
        "Detayı Gör": "View Details",
        "Aktif": "Active",
        "Aktif rezervasyon yok": "No active reservations",
        "İptal edilen rezervasyon yok": "No cancelled reservations",
        "Bir hizmet detayından rezervasyon talebi oluşturabilirsiniz.": "You can create a reservation request from service details.",
        "Tamamlanan veya reddedilen rezervasyonlar burada görünür.": "Completed or rejected reservations will appear here.",
        "İptal edilen rezervasyonlar burada görünür.": "Cancelled reservations will appear here.",
        "Bu rezervasyon talebini iptal etmek istediğinize emin misiniz?": "Are you sure you want to cancel this reservation request?",
        "Detay": "Detail",
        "İptal Et": "Cancel",
        "Vazgeç": "Cancel",
        "Müşteri": "Customer",
        "Hizmet": "Service",
        "Oluşturulma Tarihi": "Creation Date",
        "Bilgiler": "Details",

        // Expert Homepage Subtitles
        "Bekleyen ve yaklaşan talepleri görüntüle": "View pending and upcoming requests",
        "Müşteri taleplerini görüntüleyin": "View customer requests",

        // Reset Password View
        "Mevcut şifreni doğrula ve yeni şifreni belirle.": "Verify your current password and set your new one.",
        "Mevcut şifre": "Current password",
        "Yeni şifre": "New password",
        "Yeni şifre tekrar": "Confirm new password",
        "ŞİFREYİ GÜNCELLE": "UPDATE PASSWORD",
        "Mevcut şifreni mi unuttun?": "Forgot your current password?",
        "Mevcut şifreniz 6 karakterden kısa olamaz.": "Your current password cannot be shorter than 6 characters.",
        "Girdiğiniz şifreler birbiriyle eşleşmiyor.": "The passwords you entered do not match.",
        "Şifreler eşleşiyor.": "Passwords match.",
        "Yeni şifreniz mevcut şifrenizle aynı olamaz.": "Your new password cannot be the same as your current password.",
        "Şifreniz ardışık karakterler içeriyor (ör: 123, abc).": "Your password contains sequential characters (e.g. 123, abc).",
        "Şifreniz tekrar eden karakterler içeriyor (ör: aaa, 111).": "Your password contains repeating characters (e.g. aaa, 111).",
        "Şifre Gereksinimleri": "Password Requirements",
        "En az 6 karakter": "At least 6 characters",
        "En az 1 büyük harf (A-Z)": "At least 1 uppercase letter (A-Z)",
        "En az 1 küçük harf (a-z)": "At least 1 lowercase letter (a-z)",
        "En az 1 rakam (0-9)": "At least 1 digit (0-9)",
        "En az 1 özel karakter (!@#$%&*)": "At least 1 special character (!@#$%&*)",
        "Şifre Gücü:": "Password Strength:",
        "İyi": "Good",
        "Oturum Hatası": "Session Error",
        "Aktif bir oturum veya e-posta bulunamadı.": "Active session or email not found.",
        "Uygulamadan çıkış yapıp tekrar giriş yapın.": "Log out from the application and log in again.",
        "Şifre Güncellendi ✓": "Password Updated ✓",
        "Şifreniz başarıyla değiştirildi. Bir sonraki girişinizde yeni şifrenizi kullanmanız gerekmektedir.": "Your password has been successfully changed. You must use your new password next time you log in.",
        "E-posta Bulunamadı": "Email Not Found",
        "Şifre sıfırlama bağlantısı göndermek için hesabınıza bağlı bir e-posta bulunamadı.": "No email associated with your account was found to send the password reset link.",
        "Profil bilgilerinizden e-posta adresinizi kontrol edin.": "Please check your email address in your profile info.",
        "Sıfırlama E-postası Gönderildi": "Reset Email Sent",
        "%@ adresine şifre sıfırlama bağlantısı gönderildi.": "A password reset link has been sent to %@.",
        "Şifre Doğrulanamadı": "Password Verification Failed",
        "Girdiğiniz mevcut şifre hatalı.": "The current password you entered is incorrect.",
        "Şifrenizi hatırlamıyorsanız \"Şifremi Unuttum\" ile sıfırlayabilirsiniz.": "If you don't remember your password, you can reset it using \"Forgot Password\".",
        "Zayıf Şifre": "Weak Password",
        "Yeni şifreniz güvenlik standartlarını karşılamıyor.": "Your new password does not meet security standards.",
        "Büyük/küçük harf, rakam ve özel karakter kombinasyonu kullanın.": "Use a combination of uppercase/lowercase letters, digits, and special characters.",
        "Oturum Süresi Doldu": "Session Expired",
        "Bu işlem için yakın zamanda giriş yapılmış olması gerekiyor.": "This operation requires a recent login.",
        "Çıkış yapıp tekrar giriş yapın ve hemen şifre değiştirin.": "Log out, log in again, and change your password immediately.",
        "Bağlantı Hatası": "Connection Error",
        "Sunucuyla iletişim kurulamadı.": "Could not communicate with the server.",
        "İnternet bağlantınızı kontrol edip tekrar deneyin.": "Check your internet connection and try again.",
        "Çok Fazla Deneme": "Too Many Attempts",
        "Çok fazla başarısız deneme yapıldı.": "Too many failed attempts have been made.",
        "En az 5 dakika bekleyip tekrar deneyin.": "Wait at least 5 minutes and try again.",
        "Hesap Askıya Alındı": "Account Suspended",
        "Hesabınız devre dışı bırakılmış.": "Your account has been disabled.",
        "destek@uzmanagel.com adresinden bize ulaşın.": "Contact us at destek@uzmanagel.com.",
        "Sunucu Hatası": "Server Error",
        "Firebase sunucularında beklenmeyen bir hata oluştu.": "An unexpected error occurred on Firebase servers.",
        "Birkaç dakika bekleyip tekrar deneyin.": "Wait a few minutes and try again.",
        "Beklenmeyen Hata": "Unexpected Error",
        "mevcut şifreniz doğrulanırken": "while verifying your current password",
        "yeni şifreniz kaydedilirken": "while saving your new password",
        "%@ bir hata oluştu (Kod: %d).": "An error occurred %@ (Code: %d).",
        "Tekrar deneyin. Sorun devam ederse destek ekibimize başvurun.": "Try again. If the problem persists, contact our support team.",
        "Güvenlik gereği yeniden oturum açmanız gerekebilir: ": "You may need to log in again for security: ",

        // UserInfoEditView Password Changes
        "En az 8 karakter": "At least 8 characters",
        "Büyük ve küçük harf": "Uppercase and lowercase",
        "En az 1 rakam": "At least 1 number",
        "Özel karakter (!@#$...)": "Special character (!@#$...)",
        "Şifre Değiştirilemedi": "Could not change password",

        // Notification Preferences
        "Tüm Bildirimler": "All Notifications",
        "Bu seçenek kapalıysa uygulama içindeki tüm bildirim tercihleri pasif kabul edilir.": "If this option is turned off, all notification preferences within the app are considered inactive.",
        "İzin Durumu": "Permission Status",
        "iOS Bildirim İzni": "iOS Notification Permission",
        "Kontrol ediliyor...": "Checking...",
        "İzni Yeniden Kontrol Et": "Re-check Permission",
        "Rezervasyon Bildirimleri": "Reservation Notifications",
        "Mesaj Bildirimleri": "Message Notifications",
        "Kampanya Bildirimleri": "Campaign Notifications",
        "Bilgi": "Information",
        "Bu tercihler şu an cihazda saklanır. Push notification sistemi eklendiğinde Firebase bildirim akışıyla birlikte kullanılabilir.": "These preferences are currently saved on the device. When push notifications are integrated, they will work with the Firebase notification pipeline.",
        "Bildirim Tercihleri": "Notification Preferences",
        "Bildirim İzni Kapalı": "Notification Permission Off",
        "Bildirim izni daha önce kapatılmış. Tekrar açmak için iPhone Ayarları üzerinden UzmanaGel bildirim izinlerini açmanız gerekir.": "Notification permission was previously turned off. To turn it back on, you need to enable notifications for UzmanaGel in iPhone Settings.",
        "İzin verildi": "Permission granted",
        "İzin verilmedi": "Permission denied",
        "İzin alınamadı": "Could not get permission",
        "İzin kapalı": "Permission off",
        "Bilinmiyor": "Unknown",
        "Sorulmadı": "Not asked",
        "Geçmiş izin": "Provisional permission",
        "Geçici izin": "Ephemeral permission",
        "Öneri: ": "Suggestion: ",
        
        // Location Picker Sheet
        "Mevcut Konumumu Kullan": "Use My Current Location",
        "Konum alınıyor…": "Getting location...",
        "Konum izni verilmedi. Ayarlardan açabilirsiniz.": "Location permission denied. You can enable it in Settings.",
        "Otomatik Konum": "Automatic Location",
        "Şehir ve İlçe Seçin": "Select City & District",
        "Şehir veya ilçe ara…": "Search city or district...",
        "Konum Seçin": "Select Location",
        
        // Service Detail Page & Working Hours
        "Deneyim": "Experience",
        "Yıl": "Years",
        "İş Tamamlandı": "Jobs Completed",
        "Hemen": "Instant",
        "Yanıt Süresi": "Response Time",
        "Bu hizmet sağlayıcı henüz detaylı bir açıklama girmemiş.": "This service provider hasn't entered a detailed description yet.",
        "Hizmetler & Fiyatlar": "Services & Pricing",
        "Portföy / Galeri": "Portfolio / Gallery",
        "Henüz portföy görseli eklenmemiş.": "No portfolio images added yet.",
        "Çalışma Saatleri": "Working Hours",
        "Çalışma saatleri henüz girilmemiş.": "Working hours have not been entered yet.",
        "Kapalı": "Closed",
        "Pazartesi": "Monday",
        "Salı": "Tuesday",
        "Çarşamba": "Wednesday",
        "Perşembe": "Thursday",
        "Cuma": "Friday",
        "Cumartesi": "Saturday",
        "Pazar": "Sunday",
        "Konum": "Location",
        "Yol Tarifi Al": "Get Directions",
        "Sohbet Açılıyor...": "Opening Chat...",
        "Uzman bilgisi bulunamadı.": "Expert information not found.",
        "Yorumları Gör": "See Reviews",
        "yarım saat": "half hour",
        "saat": "hour",
        "günlük": "daily",
        "su tesisatı bakım": "Plumbing maintenance"
    ]
}

extension String {
    var localized: String {
        return LanguageManager.shared.translate(self)
    }
    
    func decodeBase64ToImage() -> UIImage? {
        var cleanString = self
        if cleanString.hasPrefix("data:image") {
            let components = cleanString.components(separatedBy: ",")
            if components.count > 1 {
                cleanString = components[1]
            }
        }
        guard let data = Data(base64Encoded: cleanString) else { return nil }
        return UIImage(data: data)
    }
}
