import SwiftUI
import Combine

@MainActor
class LanguageManager: ObservableObject {
    static let shared = LanguageManager()
    
    @AppStorage("pref_language") var languageCode: String = "tr" {
        didSet {
            // Notify SwiftUI views to update
            objectWillChange.send()
        }
    }
    
    func translate(_ key: String) -> String {
        if languageCode == "en" {
            return translations[key] ?? key
        }
        return key
    }
    
    
    private let translations: [String: String] = [
        "Tercihler": "Preferences",
        "Profil": "Profile",
        "Hesap Bilgileri": "Account Info",
        "Kişisel Bilgiler": "Personal Info",
        "Bilgilerinizi ve şifrenizi güncelleyin": "Update your info & password",
        "Adreslerim": "My Addresses",
        "Kayıtlı teslimat adresleri": "Saved delivery addresses",
        "Ödeme Yöntemleri": "Payment Methods",
        "Kayıtlı kredi kartları ve cüzdan": "Saved cards and wallet",
        "Ayarlar ve Tercihler": "Settings & Preferences",
        "Bildirim, tema ve dil ayarları": "Notification, theme and language settings",
        "Yardım ve Destek": "Help & Support",
        "Sıkça sorulan sorular ve destek talepleri": "FAQs and support tickets",
        "Çıkış Yap": "Log Out",
        "Oturumu sonlandır": "End session",
        "TERCİHLER": "PREFERENCES",
        "GÜVENLİK": "SECURITY",
        "Giriş Yap": "Log In",
        "Kayıt Ol": "Sign Up",
        "Favorilerim": "My Favorites",
        "Şifre Değiştir": "Change Password",
        "Telefon Doğrulama": "Phone Verification",
        "E-posta Doğrulama": "Email Verification",
        "Kullanıcı Bilgileri": "User Information",
        "Ödeme Yöntemlerim": "My Payment Methods",
        "Kayıtlı kartlarınız ve Apple Pay": "Saved cards & Apple Pay",
        "Geçmiş ve Favoriler": "History & Favorites",
        "Geçmiş siparişleriniz ve favori ustalar": "Your past orders and favorite experts",
        "Yardım": "Help",
        "Destek": "Support",
        "Yardım merkezi ve müşteri hizmetleri": "Help center & customer service",
        "Destek ve Yardım Ekranı": "Support & Help Screen",

        // Admin Panel Translations
        "Yönetim Paneli": "Admin Panel",
        "Yönetici": "ADMIN",
        "YÖNETİCİ": "ADMIN",
        "Admin Hesabı": "Admin Account",
        "Platform yönetimi ve moderasyon paneli": "Platform management & moderation panel",
        "Yönetim Araçları": "Management Tools",
        "Uzman Başvuruları ve Belgeler": "Expert Applications & Documents",
        "Bekleyen uzman başvurularını ve doğrulama belgelerini incele.": "Review pending expert applications & verification documents.",
        "Uzman Başvuru Geçmişi": "Expert Application History",
        "Onay, ret ve eksik belge kararlarını görüntüle.": "View approval, rejection and document decision history.",
        "Bildirilen Yorumlar": "Reported Reviews",
        "Kullanıcıların bildirdiği yorumları incele.": "Review user-reported comments and feedback.",
        "Moderasyon Geçmişi": "Moderation History",
        "Tamamlanan yorum moderasyon işlemlerini görüntüle.": "View completed review moderation logs.",
        "Başvurular": "Applications",
        "Moderasyon": "Moderation",
        "Arşiv": "Archive",
        
        // Admin - Expert Applications
        "Uzman Başvuruları": "Expert Applications",
        "Bekleyen Başvuru Yok": "No Pending Applications",
        "Yeni bir uzman başvurusu gönderildiğinde burada görünecektir.": "When a new expert application is submitted, it will appear here.",
        "Listeyi Yenile": "Refresh List",
        "Başvurular yükleniyor...": "Loading applications...",
        "Başvuru geçmişi": "Application history",
        
        // Admin - Reported Reviews
        "Rapor durumu": "Report status",
        "İncelemede": "Under Review",
        "Bekleyen Bildirim Yok": "No Pending Reports",
        "İncelemede Yorum Yok": "No Reviews Under Review",
        "İncelenmesi gereken yeni bir yorum bildirimi bulunmuyor.": "There are no new comment reports to review.",
        "İleri incelemeye alınmış bir yorum bulunmuyor.": "There are no reviews marked for further review.",
        "Yenile": "Refresh",
        "Bildirimler yükleniyor...": "Loading reports...",
        "Raporu Reddet": "Reject Report",
        "İncelemeye Al": "Move to Under Review",
        "Yorumu Kaldır": "Remove Review",
        "Rapor reddedilsin mi?": "Reject this report?",
        "Yorum incelemeye alınsın mı?": "Move review to under review?",
        "Yorum kaldırılsın mı?": "Remove this review?",
        "Rapor kapatılacak ancak yorum yayında kalacak.": "Report will be closed but review remains published.",
        "Rapor ileri inceleme kuyruğuna taşınacak.": "Report will be moved to further review queue.",
        "Yorum yayından kaldırılacak ve moderasyon arşivine kaydedilecek.": "Review will be removed from publication and saved to moderation archive.",
        
        // Admin - Application History
        "Başvuru Geçmişi": "Application History",
        "Başvuru Geçmişi Yok": "No Application History",
        "Tamamlanan uzman başvuru kararları burada görünecek.": "Completed expert application decisions will appear here.",
        "Başvuru geçmişi yükleniyor...": "Loading application history...",
        "Geçmiş Yüklenemedi": "Failed to Load History",
        "Eksik Belge": "Missing Document",
        "İşlem": "Action",
        "Taslak": "Draft",
        "Belirtilmemiş": "Not Specified",
        "Önceki": "Previous",
        "Admin Açıklaması": "Admin Note",
        "İşlemi yapan": "Processed by",
        
        // Admin - Moderation History
        "Moderasyon Geçmişi Yok": "No Moderation History",
        "Tamamlanan yorum moderasyon işlemleri burada görüntülenecektir.": "Completed review moderation operations will be displayed here.",
        "Rapor Reddedildi": "Report Rejected",
        "Yorum Kaldırıldı": "Review Removed",
        "Kategori:": "Category:",
        "YORUM İÇERİĞİ": "REVIEW CONTENT",
        "Kullanıcı:": "User:",
        "Yorum ID:": "Comment ID:",
        "Admin Notu": "Admin Note",
        "Geçmiş yükleniyor...": "Loading history...",
        "Geçmiş yüklenemedi": "Failed to load history",
        
        // Report Categories & Common Badges
        "Spam / Reklam": "Spam / Advertising",
        "Diğer": "Other",
        "Sahte Yorum": "Fake Review",
        "Uygunsuz İçerik": "Inappropriate Content",
        "Taciz / Hakaret": "Harassment / Insult",
        "Telif / Gizlilik İhlali": "Copyright / Privacy Violation",
        "Bilinmeyen kullanıcı": "Unknown user",
        "Yorum bulunamadı.": "Review not found.",

        
        // Preferences Page / View
        "BİLDİRİM AYARLARI": "NOTIFICATION SETTINGS",
        "Bildirim Ayarları": "Notification Settings",
        "Anlık Bildirimler (Push)": "Push Notifications",
        "E-posta Bildirimleri": "Email Notifications",
        "SMS Bildirimleri": "SMS Notifications",
        "Rezervasyon Güncellemeleri": "Booking Updates",
        "Kampanya ve Tanıtımlar": "Campaigns & Promos",
        "Sistem ve Güvenlik": "System & Security",
        "Rezervasyon": "Bookings",
        "Kampanya & Promosyon": "Campaigns & Promos",
        "Sistem Bildirimleri": "System Notifications",
        "Bildirim izni reddedilmiş.": "Notification permission denied.",
        "Bildirim Türleri": "Notification Types",
        "Profilim Herkese Açık": "My Profile is Public",
        "Veri Toplama Onayı": "Data Collection Consent",
        "GÖRÜNÜM AYARLARI": "APPEARANCE SETTINGS",
        "Görünüm Ayarları": "Appearance Settings",
        "Tema": "Theme",
        "Sistem": "System",
        "Açık": "Light",
        "Koyu": "Dark",
        "DİL SEÇİMİ": "LANGUAGE SELECTION",
        "Dil Ayarları": "Language Settings",
        "Uygulama Dili": "App Language",
        "Tema Seçimi": "Theme Selection",
        "Dil": "Language",
        "GİZLİLİK AYARLARI": "PRIVACY SETTINGS",
        "Gizlilik Ayarları": "Privacy Settings",
        "Konum Paylaşımı": "Location Sharing",
        "Profil Görünürlüğü (Herkese Açık)": "Profile Visibility (Public)",
        "Kullanım Verisi Analiz İzni": "Data Collection Analytics",
        "Tüm tercihler otomatik olarak kaydedilir.": "All preferences are automatically saved.",
        "Tercihler kaydedildi!": "Preferences saved!",
        "Ayarları Kaydet": "Save Settings",
        
        // Settings Page & Terms & Help & Privacy
        "Görünüm": "Appearance",
        "Gizlilik": "Privacy",
        "KVKK / Gizlilik Politikası": "KVKK / Privacy Policy",
        "Okudum ve Kabul Ediyorum": "I Have Read and Agree",
        "Kullanım Şartları": "Terms of Service",
        "Sık Sorulan Sorular": "Frequently Asked Questions",
        "Nasıl hizmet bulabilirim?": "How can I find a service?",
        "Ana sayfadan hizmetleri inceleyebilir, arama ve filtreleme seçeneklerini kullanarak ihtiyacınıza uygun hizmetleri bulabilirsiniz.": "You can explore services from the homepage, using search and filtering options to find services that suit your needs.",
        "Bir hizmeti favorilere nasıl eklerim?": "How do I add a service to favorites?",
        "Hizmet kartındaki veya hizmet detay sayfasındaki kalp ikonuna dokunarak hizmeti favorilerinize ekleyebilirsiniz.": "You can add a service to your favorites by tapping the heart icon on the service card or detail page.",
        "Rezervasyon nasıl oluşturulur?": "How do I create a booking?",
        "Hizmet detay sayfasına girip rezervasyon oluşturma butonuna dokunarak tarih ve not bilgisiyle rezervasyon talebi oluşturabilirsiniz.": "You can create a booking request with a date and notes by going to the service detail page and tapping the create booking button.",
        "Rezervasyonumu nasıl iptal ederim?": "How do I cancel my booking?",
        "Rezervasyonlarım sayfasından aktif rezervasyonunuzu seçip iptal işlemini gerçekleştirebilirsiniz.": "You can select your active booking on the My Bookings page and cancel it.",
        "Uzmanla nasıl mesajlaşırım?": "How do I message with an expert?",
        "Hizmet detay sayfasından uzmanla mesajlaşma akışını başlatabilir, Mesajlar sayfasından mevcut konuşmalarınızı takip edebilirsiniz.": "You can start messaging from the service detail page and follow your ongoing chats from the Messages page.",
        "Bildirim ayarlarımı nereden değiştirebilirim?": "Where can I change my notification settings?",
        "Ayarlar sayfasındaki Bildirim Tercihleri bölümünden rezervasyon, mesaj, sistem ve kampanya bildirimlerini yönetebilirsiniz.": "You can manage booking, message, system, and campaign notifications from the Notification Preferences section on the Settings page.",
        "Adres bilgilerimi nereden yönetebilirim?": "Where can I manage my address information?",
        "Profil sayfasındaki Adreslerim bölümünden kayıtlı adreslerinizi görüntüleyebilir ve düzenleyebilirsiniz.": "You can view and edit your saved addresses from the My Addresses section on the Profile page.",
        "Profil bilgilerimi nasıl güncellerim?": "How do I update my profile information?",
        "Profil sayfasındaki Düzenle veya Kullanıcı Bilgileri alanından ad, iletişim ve profil bilgilerinizi güncelleyebilirsiniz.": "You can update your name, contact, and profile info from the Edit or User Information section on the Profile page.",
        "Uzman olmak için ne yapmalıyım?": "What should I do to become an expert?",
        "Uzman başvuru sürecini tamamlayarak gerekli bilgileri ve doğrulamaları gönderebilirsiniz.": "You can complete the expert application process by submitting the required info and verifications.",
        "Sorun Bildirme": "Reporting an Issue",
        "Bir sorun yaşarsanız ekran görüntüsü, işlem adımı ve hesap bilgilerinizle birlikte destek ekibine iletmeniz sorunun daha hızlı incelenmesini sağlar.": "If you experience an issue, sending a screenshot, steps taken, and your account info to the support team helps examine the issue faster.",
        "Bu sayfa, UzmanaGel uygulamasının temel kullanım kurallarını özetler.": "This page summarizes the basic usage rules of the UzmanaGel application.",
        "UzmanaGel, kullanıcıların ihtiyaç duydukları hizmetler için uygun uzmanlara ulaşmasını sağlayan bir platformdur.": "UzmanaGel is a platform that enables users to connect with suitable experts for the services they need.",
        "1. Hizmetin Kullanımı": "1. Use of the Service",
        "UzmanaGel, kullanıcıların ihtiyaç duydukları hizmetler için uygun uzmanlarla iletişim kurmasını sağlayan bir platformdur. Kullanıcılar, uygulamayı doğru ve güncel bilgilerle kullanmakla sorumludur.": "UzmanaGel is a platform enabling users to communicate with suitable experts for needed services. Users are responsible for using the app with accurate and updated information.",
        "2. Uzman ve Kullanıcı Sorumlulukları": "2. Expert and User Responsibilities",
        "Uzmanlar sundukları hizmet bilgilerini doğru şekilde paylaşmalıdır. Kullanıcılar oluşturdukları rezervasyon taleplerinde doğru iletişim ve ihtiyaç bilgisi vermelidir.": "Experts must accurately share information about the services they provide. Users must provide accurate contact and requirements in their booking requests.",
        "3. Rezervasyonlar": "3. Bookings",
        "Rezervasyon talepleri uygulama üzerinden oluşturulur. Rezervasyonun kesinleşmesi, ilgili uzmanın talebi değerlendirmesine bağlıdır. Kullanıcılar aktif rezervasyon taleplerini iptal edebilir.": "Booking requests are created through the application. Confirmation depends on the expert's evaluation. Users may cancel active booking requests.",
        "4. Mesajlaşma": "4. Messaging",
        "Kullanıcılar ve uzmanlar, hizmet sürecini takip etmek için uygulama içi mesajlaşma özelliğini kullanabilir. Uygunsuz, yanıltıcı veya kötüye kullanım içeren mesajlardan kullanıcı sorumludur.": "Users and experts can use in-app messaging to track the service process. Users are responsible for inappropriate, misleading, or abusive messages.",
        "5. Gizlilik": "5. Privacy",
        "Kullanıcı verileri, uygulamanın hizmet sunabilmesi için gerekli olan kapsamda işlenir. Gizlilik ve KVKK detayları ilgili gizlilik sayfasında açıklanır.": "User data is processed to the extent necessary for the app to provide its services. Privacy and KVKK details are explained on the respective privacy page.",
        "6. Değişiklikler": "6. Modifications",
        "UzmanaGel, kullanım şartlarını uygulama geliştikçe güncelleyebilir. Güncel şartlar uygulama içinde kullanıcıya sunulur.": "UzmanaGel may update its terms of service as the application evolves. Current terms are presented to the user within the application.",
        "Dil Seçimi": "Language Selection",
        "Türkçe": "Turkish",
        "İngilizce": "English",
        
        // General UI & Loadings
        "Profil yükleniyor...": "Loading profile...",
        "Tercihleriniz yükleniyor...": "Loading preferences...",
        "Hata Oluştu": "Error Occurred",
        "Bir Hata Oluştu": "An Error Occurred",
        "Tekrar Dene": "Retry",
        "Kapat": "Close",
        
        // Homepage & History
        "Hoş Geldiniz": "Welcome",
        "Uzman Bul": "Find an Expert",
        "Ara": "Search",
        "Kategoriler": "Categories",
        "Popüler Hizmetler": "Popular Services",
        "Tümünü Gör": "See All",
        "Geçmiş": "Past",
        "Favoriler": "Favorites",
        "Verileriniz yükleniyor...": "Loading your data...",
        "Kartlarınız yükleniyor...": "Loading your cards...",
        "Adresleriniz yükleniyor...": "Loading your addresses...",
        "Henüz rezervasyon bulunmuyor.": "No bookings found yet.",
        "Favori uzmanınız bulunmuyor.": "No favorite experts found.",
        
        // Edit Profile Page & SMS / Crop
        "Fotoğrafı Değiştir": "Change Photo",
        "Ad Soyad": "Full Name",
        "E-posta": "Email",
        "E-posta değişikliği doğrulama maili gerektirir.": "Email change requires a validation email.",
        "Telefon Numarası": "Phone Number",
        "Doğrula": "Verify",
        "Değişiklikleri Kaydet": "Save Changes",
        "Mevcut Şifre": "Current Password",
        "Yeni Şifre": "New Password",
        "Yeni Şifre (Tekrar)": "Confirm New Password",
        "Şifre Gücü: ": "Password Strength: ",
        "Çok Zayıf": "Very Weak",
        "Zayıf": "Weak",
        "Orta": "Medium",
        "Güçlü": "Strong",
        "Çok Güçlü": "Very Strong",
        "Şifreyi Güncelle": "Update Password",
        "Bilgileri Düzenle": "Edit Profile",
        "SMS Doğrulama": "SMS Verification",
        "%@ numaralı telefona gönderilen 4 haneli doğrulama kodunu girin.\n(Mock Kodu: 1234)": "Enter the 4-digit verification code sent to %@.\n(Mock Code: 1234)",
        "Doğrulama Kodu": "Verification Code",
        "Onayla ve Telefonu Güncelle": "Confirm & Update Phone",
        "Doğrulama": "Verification",
        "Görseli Kırp / Ölçeklendir": "Crop / Scale Image",
        "Ölçek: %%%d": "Scale: %%%d",
        "Kırp ve Uygula": "Crop & Apply",
        "Kırpma": "Cropping",
        "Profil bilgileriniz başarıyla güncellendi.": "Your profile info has been successfully updated.",
        "Yeni şifreler eşleşmiyor.": "New passwords do not match.",
        "Şifreniz başarıyla değiştirildi.": "Your password has been successfully changed.",
        "Telefon numaranız doğrulandı.": "Your phone number has been verified.",
        
        // Homepage & Login & Logout & Categories
        "Konumunuz": "Your Location",
        "Hizmet, uzman veya kategori ara…": "Search services, experts or categories...",
        "Hizmet, uzman veya kategori ara...": "Search services, experts or categories...",
        "(0 yorum)": "(0 reviews)",
        "başlangıç fiyatı": "starting price",
        "Hoşgeldiniz": "Welcome",
        "Beni Hatırla": "Remember Me",
        "Şifremi Unuttum": "Forgot Password",
        "GİRİŞ YAP": "LOG IN",
        "VEYA": "OR",
        "Hesabın yok mu?": "Don't have an account?",
        "Uzman mısın?": "Are you an expert?",
        "Başvuru Yap": "Apply Now",
        "Hesabınızdan çıkmak istediğinizden emin misiniz?": "Are you sure you want to log out of your account?",
        "İptal": "Cancel",
        "su tesisatı": "plumbing",
        "Kombi & Klima Bakımı": "Boiler & AC Maintenance",
        "Yazılım & Teknoloji": "Software & Tech",
        "Boya & Badana": "Painting & Whitewash",
        "Su tesisatı bakım": "Plumbing maintenance",
        "Yıllık bakım": "Annual maintenance",
        "Mobil uygulama (iOS)": "Mobile app (iOS)",
        "Profesyonel Boya": "Professional Painting",
        
        // Side Menu & Customer Profile View
        "Ana Sayfa": "Home",
        "Profilim": "My Profile",
        "Mesajlar": "Messages",
        "Ayarlar": "Settings",
        "Kullanıcı": "User",
        "Yeni Üye": "New Member",
        "%d Ay Üye": "%d Months Member",
        "%d Yıl Üye": "%d Years Member",
        "Siparişlerim": "My Orders",
        "İLETİŞİM BİLGİLERİ": "CONTACT INFO",
        "Telefon": "Phone",
        "DOĞRULANDI": "VERIFIED",
        "DOĞRULA": "VERIFY",
        "HESAP AYARLARI": "ACCOUNT SETTINGS",
        "GEÇMİŞ & FAVORİLER": "HISTORY & FAVORITES",
        "Düzenle": "Edit",
        
        // Filter Sheet
        "Kategori": "Category",
        "Tüm Kategoriler": "All Categories",
        "Şehir": "City",
        "Tüm Şehirler": "All Cities",
        "Fiyat Aralığı": "Price Range",
        "Sıralama": "Sort By",
        "Varsayılan": "Default",
        "Fiyat: Düşükten Yükseğe": "Price: Low to High",
        "Fiyat: Yüksekten Düşüğe": "Price: High to Low",
        "Sıfırla": "Reset",
        "Uygula": "Apply",
        "Filtrele & Sırala": "Filter & Sort",
        "Filtre aktif": "Filter active",
        "Temizle": "Clear",
        
        // Messages Page & Settings Page
        "Henüz mesaj bulunmuyor.": "No messages found yet.",
        "Uygulama": "App",
        "Bildirimler": "Notifications",
        "KVKK ve Gizlilik": "KVKK & Privacy",
        "Hakkında": "About",
        
        // User Info Edit View
        "Ad": "First Name",
        "Soyad": "Last Name",
        "Doğrulandı": "Verified",
        "SMS ile Doğrula": "Verify with SMS",
        "Hesap şifreni güvenli şekilde güncelle": "Update your account password securely",
        "DEĞİŞİKLİKLERİ KAYDET": "SAVE CHANGES",
        
        // Order History & Favorites additions
        "Sipariş Geçmişim": "My Order History",
        "Sipariş Geçmişi": "Order History",
        "Tümü": "All",
        "Tamamlandı": "Completed",
        "İptal Edildi": "Cancelled",
        "Bekliyor": "Pending",
        "Değerlendir": "Rate",
        "Tekrarla": "Repeat",
        "Sipariş geçmişi bulunamadı": "No order history found",
        "Tamamlanan siparişleriniz burada görünecek.": "Your completed orders will appear here.",
        "Favorin yok": "No favorites",
        "Ana sayfadan kalp ikonuna basarak favori ekleyebilirsin.": "You can add favorites by tapping the heart icon on the homepage.",
        "Hata": "Error",
        "Tamam": "OK",
        "Bilinmeyen hata": "Unknown error",
        "Henüz favori yok": "No favorites yet",
        "Beğendiğiniz uzmanları favorilere ekleyin.": "Add the experts you like to your favorites.",
        "İletişim": "Contact",
        "Rezervasyonlarım": "My Bookings",
        
        // Reservation Statuses
        "Beklemede": "Pending",
        "Onaylandı": "Approved",
        "Reddedildi": "Rejected",

        // Reservation Detail & Sheets
        "Randevu Bilgileri": "Appointment Details",
        "Randevu Tarihi": "Appointment Date",
        "Not ekle": "Add a note",
        "Not": "Note",
        "Not eklenmemiş.": "No note added.",
        "Rezervasyon Talebi Oluştur": "Create Reservation Request",
        "Rezervasyon Detayı": "Reservation Detail",
        "İşlemler": "Actions",
        "Mesaj Gönder": "Send Message",
        "Rezervasyonu reddet": "Reject reservation",
        "Bu rezervasyonu reddetmek istediğinizden emin misiniz?": "Are you sure you want to reject this reservation?",
        "%@ adlı müşterinin rezervasyon talebini reddetmek istediğinizden emin misiniz?": "Are you sure you want to reject the reservation request of customer %@?",
        "Rezervasyonu iptal et": "Cancel reservation",
        "Bu rezervasyonu iptal etmek istediğinizden emin misiniz?": "Are you sure you want to cancel this reservation?",
        "Oturum açmış kullanıcı bulunamadı.": "Active session user not found.",
        "Bu rezervasyon için mesajlaşma yetkiniz yok.": "You do not have messaging permission for this reservation.",
        "Bu rezervasyon için karar verme yetkiniz yok.": "You do not have decision-making permission for this reservation.",
        "Bu rezervasyonu iptal edemezsiniz.": "You cannot cancel this reservation.",
        "Rezervasyon talebiniz oluşturuldu.": "Your reservation request has been created.",
        "Gelen Rezervasyonlar": "Incoming Reservations",
        "Bekleyen": "Pending",
        "Bugün": "Today",
        "Yaklaşan": "Upcoming",
        "Rezervasyonlar yükleniyor...": "Loading reservations...",
        "Rezervasyon filtresi": "Reservation filter",
        "Bekleyen rezervasyon yok": "No pending reservations",
        "Bugün için rezervasyon yok": "No reservations for today",
        "Yaklaşan rezervasyon yok": "No upcoming reservations",
        "Geçmiş rezervasyon yok": "No past reservations",
        "Müşterilerden gelen yeni rezervasyon talepleri burada görünür.": "New reservation requests from customers will appear here.",
        "Bugünkü aktif rezervasyonlar burada görünür.": "Active reservations for today will appear here.",
        "Bugünden sonraki aktif rezervasyonlar burada görünür.": "Active reservations after today will appear here.",
        "Tamamlanan, reddedilen veya iptal edilen rezervasyonlar burada görünür.": "Completed, rejected, or cancelled reservations will appear here.",
        "Kabul Et": "Accept",
        "Reddet": "Reject",
        "Detayı Gör": "View Details",
        "Aktif": "Active",
        "Aktif rezervasyon yok": "No active reservations",
        "İptal edilen rezervasyon yok": "No cancelled reservations",
        "Bir hizmet detayından rezervasyon talebi oluşturabilirsiniz.": "You can create a reservation request from service details.",
        "Tamamlanan veya reddedilen rezervasyonlar burada görünür.": "Completed or rejected reservations will appear here.",
        "İptal edilen rezervasyonlar burada görünür.": "Cancelled reservations will appear here.",
        "Bu rezervasyon talebini iptal etmek istediğinize emin misiniz?": "Are you sure you want to cancel this reservation request?",
        "Detay": "Detail",
        "İptal Et": "Cancel",
        "Vazgeç": "Cancel",
        "Müşteri": "Customer",
        "Hizmet": "Service",
        "Oluşturulma Tarihi": "Creation Date",
        "Bilgiler": "Details",

        // Expert Homepage Subtitles
        "Bekleyen ve yaklaşan talepleri görüntüle": "View pending and upcoming requests",
        "Müşteri taleplerini görüntüleyin": "View customer requests",

        // Reset Password View
        "Mevcut şifreni doğrula ve yeni şifreni belirle.": "Verify your current password and set your new one.",
        "Mevcut şifre": "Current password",
        "Yeni şifre": "New password",
        "Yeni şifre tekrar": "Confirm new password",
        "ŞİFREYİ GÜNCELLE": "UPDATE PASSWORD",
        "Mevcut şifreni mi unuttun?": "Forgot your current password?",
        "Mevcut şifreniz 6 karakterden kısa olamaz.": "Your current password cannot be shorter than 6 characters.",
        "Girdiğiniz şifreler birbiriyle eşleşmiyor.": "The passwords you entered do not match.",
        "Şifreler eşleşiyor.": "Passwords match.",
        "Yeni şifreniz mevcut şifrenizle aynı olamaz.": "Your new password cannot be the same as your current password.",
        "Şifreniz ardışık karakterler içeriyor (ör: 123, abc).": "Your password contains sequential characters (e.g. 123, abc).",
        "Şifreniz tekrar eden karakterler içeriyor (ör: aaa, 111).": "Your password contains repeating characters (e.g. aaa, 111).",
        "Şifre Gereksinimleri": "Password Requirements",
        "En az 6 karakter": "At least 6 characters",
        "En az 1 büyük harf (A-Z)": "At least 1 uppercase letter (A-Z)",
        "En az 1 küçük harf (a-z)": "At least 1 lowercase letter (a-z)",
        "En az 1 rakam (0-9)": "At least 1 digit (0-9)",
        "En az 1 özel karakter (!@#$%&*)": "At least 1 special character (!@#$%&*)",
        "Şifre Gücü:": "Password Strength:",
        "İyi": "Good",
        "Oturum Hatası": "Session Error",
        "Aktif bir oturum veya e-posta bulunamadı.": "Active session or email not found.",
        "Uygulamadan çıkış yapıp tekrar giriş yapın.": "Log out from the application and log in again.",
        "Şifre Güncellendi ✓": "Password Updated ✓",
        "Şifreniz başarıyla değiştirildi. Bir sonraki girişinizde yeni şifrenizi kullanmanız gerekmektedir.": "Your password has been successfully changed. You must use your new password next time you log in.",
        "E-posta Bulunamadı": "Email Not Found",
        "Şifre sıfırlama bağlantısı göndermek için hesabınıza bağlı bir e-posta bulunamadı.": "No email associated with your account was found to send the password reset link.",
        "Profil bilgilerinizden e-posta adresinizi kontrol edin.": "Please check your email address in your profile info.",
        "Sıfırlama E-postası Gönderildi": "Reset Email Sent",
        "%@ adresine şifre sıfırlama bağlantısı gönderildi.": "A password reset link has been sent to %@.",
        "Şifre Doğrulanamadı": "Password Verification Failed",
        "Girdiğiniz mevcut şifre hatalı.": "The current password you entered is incorrect.",
        "Şifrenizi hatırlamıyorsanız \"Şifremi Unuttum\" ile sıfırlayabilirsiniz.": "If you don't remember your password, you can reset it using \"Forgot Password\".",
        "Zayıf Şifre": "Weak Password",
        "Yeni şifreniz güvenlik standartlarını karşılamıyor.": "Your new password does not meet security standards.",
        "Büyük/küçük harf, rakam ve özel karakter kombinasyonu kullanın.": "Use a combination of uppercase/lowercase letters, digits, and special characters.",
        "Oturum Süresi Doldu": "Session Expired",
        "Bu işlem için yakın zamanda giriş yapılmış olması gerekiyor.": "This operation requires a recent login.",
        "Çıkış yapıp tekrar giriş yapın ve hemen şifre değiştirin.": "Log out, log in again, and change your password immediately.",
        "Bağlantı Hatası": "Connection Error",
        "Sunucuyla iletişim kurulamadı.": "Could not communicate with the server.",
        "İnternet bağlantınızı kontrol edip tekrar deneyin.": "Check your internet connection and try again.",
        "Çok Fazla Deneme": "Too Many Attempts",
        "Çok fazla başarısız deneme yapıldı.": "Too many failed attempts have been made.",
        "En az 5 dakika bekleyip tekrar deneyin.": "Wait at least 5 minutes and try again.",
        "Hesap Askıya Alındı": "Account Suspended",
        "Hesabınız devre dışı bırakılmış.": "Your account has been disabled.",
        "destek@uzmanagel.com adresinden bize ulaşın.": "Contact us at destek@uzmanagel.com.",
        "Sunucu Hatası": "Server Error",
        "Firebase sunucularında beklenmeyen bir hata oluştu.": "An unexpected error occurred on Firebase servers.",
        "Birkaç dakika bekleyip tekrar deneyin.": "Wait a few minutes and try again.",
        "Beklenmeyen Hata": "Unexpected Error",
        "mevcut şifreniz doğrulanırken": "while verifying your current password",
        "yeni şifreniz kaydedilirken": "while saving your new password",
        "%@ bir hata oluştu (Kod: %d).": "An error occurred %@ (Code: %d).",
        "Tekrar deneyin. Sorun devam ederse destek ekibimize başvurun.": "Try again. If the problem persists, contact our support team.",
        "Güvenlik gereği yeniden oturum açmanız gerekebilir: ": "You may need to log in again for security: ",

        // UserInfoEditView Password Changes
        "En az 8 karakter": "At least 8 characters",
        "Büyük ve küçük harf": "Uppercase and lowercase",
        "En az 1 rakam": "At least 1 number",
        "Özel karakter (!@#$...)": "Special character (!@#$...)",
        "Şifre Değiştirilemedi": "Could not change password",

        // Notification Preferences
        "Tüm Bildirimler": "All Notifications",
        "Bu seçenek kapalıysa uygulama içindeki tüm bildirim tercihleri pasif kabul edilir.": "If this option is turned off, all notification preferences within the app are considered inactive.",
        "İzin Durumu": "Permission Status",
        "iOS Bildirim İzni": "iOS Notification Permission",
        "Kontrol ediliyor...": "Checking...",
        "İzni Yeniden Kontrol Et": "Re-check Permission",
        "Rezervasyon Bildirimleri": "Reservation Notifications",
        "Mesaj Bildirimleri": "Message Notifications",
        "Kampanya Bildirimleri": "Campaign Notifications",
        "Bilgi": "Information",
        "Bu tercihler şu an cihazda saklanır. Push notification sistemi eklendiğinde Firebase bildirim akışıyla birlikte kullanılabilir.": "These preferences are currently saved on the device. When push notifications are integrated, they will work with the Firebase notification pipeline.",
        "Bildirim Tercihleri": "Notification Preferences",
        "Bildirim İzni Kapalı": "Notification Permission Off",
        "Bildirim izni daha önce kapatılmış. Tekrar açmak için iPhone Ayarları üzerinden UzmanaGel bildirim izinlerini açmanız gerekir.": "Notification permission was previously turned off. To turn it back on, you need to enable notifications for UzmanaGel in iPhone Settings.",
        "İzin verildi": "Permission granted",
        "İzin verilmedi": "Permission denied",
        "İzin alınamadı": "Could not get permission",
        "İzin kapalı": "Permission off",
        "Bilinmiyor": "Unknown",
        "Sorulmadı": "Not asked",
        "Geçmiş izin": "Provisional permission",
        "Geçici izin": "Ephemeral permission",
        "Öneri: ": "Suggestion: ",
        
        // Location Picker Sheet
        "Mevcut Konumumu Kullan": "Use My Current Location",
        "Konum alınıyor…": "Getting location...",
        "Konum izni verilmedi. Ayarlardan açabilirsiniz.": "Location permission denied. You can enable it in Settings.",
        "Otomatik Konum": "Automatic Location",
        "Şehir ve İlçe Seçin": "Select City & District",
        "Şehir veya ilçe ara…": "Search city or district...",
        "Konum Seçin": "Select Location",
        
        // Service Detail Page & Working Hours
        "Deneyim": "Experience",
        "Yıl": "Years",
        "İş Tamamlandı": "Jobs Completed",
        "Hemen": "Instant",
        "Yanıt Süresi": "Response Time",
        "Bu hizmet sağlayıcı henüz detaylı bir açıklama girmemiş.": "This service provider hasn't entered a detailed description yet.",
        "Hizmetler & Fiyatlar": "Services & Pricing",
        "Portföy / Galeri": "Portfolio / Gallery",
        "Henüz portföy görseli eklenmemiş.": "No portfolio images added yet.",
        "Çalışma Saatleri": "Working Hours",
        "Çalışma saatleri henüz girilmemiş.": "Working hours have not been entered yet.",
        "Kapalı": "Closed",
        "Pazartesi": "Monday",
        "Salı": "Tuesday",
        "Çarşamba": "Wednesday",
        "Perşembe": "Thursday",
        "Cuma": "Friday",
        "Cumartesi": "Saturday",
        "Pazar": "Sunday",
        "Konum": "Location",
        "Yol Tarifi Al": "Get Directions",
        "Sohbet Açılıyor...": "Opening Chat...",
        "Uzman bilgisi bulunamadı.": "Expert information not found.",
        "Yorumları Gör": "See Reviews",
        "yarım saat": "half hour",
        "saat": "hour",
        "günlük": "daily",
        "Yükleniyor...": "Loading...",
        "Geçmiş Siparişler": "Past Orders",
        "Favoriler & Arama": "Favorites & Search",
        "Sipariş Geçmişiniz Boş": "Your Order History is Empty",
        "Daha önce hiçbir hizmet siparişi oluşturmadınız.": "You haven't created any service orders before.",
        "Puan Ver": "Rate",
        "Hizmeti Yeniden Al": "Reorder Service",
        "Favori Ustalarım": "My Favorite Experts",
        "Henüz favori listenize kimseyi eklemediniz.": "You haven't added anyone to your favorites yet.",
        "Son Görüntülenenler": "Recently Viewed",
        "Henüz bir usta profiline bakmadınız.": "You haven't viewed any expert profile yet.",
        "Kayıtlı Aramalar": "Saved Searches",
        "Kayıtlı arama bulunmuyor.": "No saved searches.",
        "İletişime Geç": "Contact",
        "Sipariş bulunamadı.": "Order not found.",
        "Mesafe (km)": "Distance (km)",
        "Müsaitlik": "Availability",
        "Bugün Müsait": "Available Today",
        "Bu Hafta Müsait": "Available This Week",
        "Belirli Bir Tarih": "Specific Date",
        "Saat Aralığı": "Time Range",
        "Minimum Değerlendirme": "Minimum Rating",
        "Hızlı Seçim:": "Quick Select:",
        "Deneyim Yılı": "Years of Experience",
        "Fark etmez": "Doesn't matter",
        "Tamamlanan İş Sayısı": "Completed Jobs",
        "Sadece Sertifikalı Uzmanlar": "Certified Experts Only",
        "Hizmet Sağlayıcı Türü": "Service Provider Type",
        "Şahıs": "Individual",
        "Şirket": "Company",
        "Konumum": "My Location",
        "su tesisatı bakım": "Plumbing maintenance",
        
        // Expert Dashboard
        "Profil tamamlanma": "Profile completion",
        "dolu": "full",
        "İlan açmak için çalışma detayları, banka bilgileri ve adres bilgilerinizi Profilim sayfasından tamamlayın.": "Complete your work details, bank information, and address information from the My Profile page to open a listing.",
        "Profiliniz tamam. İlan açabilirsiniz.": "Your profile is complete. You can open a listing.",
        "Hoş geldin": "Welcome",
        "Başvuru durumu": "Application status",
        "Admin açıklaması": "Admin note",
        "Belgeleri Güncelle": "Update Documents",
        "Başvuru Onaylandı": "Application Approved",
        "Eksik Belge İsteniyor": "Missing Documents Required",
        "Başvuru Reddedildi": "Application Rejected",
        "Başvuru Taslak Durumunda": "Application in Draft Status",
        "Başvuru İnceleniyor": "Application Under Review",
        "Hızlı Erişim": "Quick Access",
        "İlanlarım": "My Listings",
        "İlanlarınızı yönetin": "Manage your listings",
        "ilan": "listings",
        "Kişisel ve iş bilgileri": "Personal and business info",
        "Müşterilerle olan konuşmalarınızı görüntüleyin": "View your conversations with customers",
        "Panel": "Dashboard",
        "Genel durum ve performans özeti": "General status and performance summary",
        "Takvim": "Calendar",
        "Çalışma programınızı görüntüleyin": "View your work schedule",
        "Finans": "Finance",
        "Kazanç ve ödeme bilgilerini görüntüleyin": "View earnings and payment information",
        "İstatistikler": "Statistics",
        "Performans ve hizmet istatistikleri": "Performance and service statistics",
        "Hizmet Yönetimi": "Service Management",
        "Hizmetlerinizi görüntüleyin": "View your services",
        "Yeni Portföy": "New Portfolio",
        "Portföy ekranını görüntüleyin": "View the portfolio screen",
        "İş Profili": "Business Profile",
        "İşletme profilinizi düzenleyin": "Edit your business profile",
        "Portföy": "Portfolio",
        "Örnek işlerinizi ekleyin": "Add your sample works",
        "fotoğraf": "photos",
        "Profil yüklenemedi": "Could not load profile",
        "Menü": "Menu",
        "Hesap ayarları ve hızlı erişim": "Account settings and quick access",
        "Bilgilerinizi düzenleyin": "Edit your information",
        "Müşteri konuşmalarınızı görüntüleyin": "View your customer conversations",
        "Yorumlar": "Reviews",
        "Müşteri yorumlarınızı görüntüleyin": "View your customer reviews",
        "Portföyünüzü yönetin": "Manage your portfolio",
        "Kazanç ve ödeme bilgileri": "Earnings and payment info",
        "Performans verileri": "Performance data",
        "Hesabınızdan çıkış yapın": "Log out of your account",
        
        // Expert Profile Page
        "Profiliniz yükleniyor...": "Loading your profile...",
        "Lütfen tekrar deneyin.": "Please try again.",
        "Tekrar dene": "Try again",
        "Müşteriler seni nasıl görüyor": "How customers see you",
        "Uzman": "Expert",
        "Fotoğrafı değiştirmek için dokunun": "Tap to change photo",
        "İlan açmak için %100 olmalı": "Must be 100% to open a listing",
        "İlan açabilirsiniz": "You can open a listing",
        "Onay bekleniyor": "Pending approval",
        "Belgeleri güncelleyip tekrar gönderin": "Update documents and resubmit",
        "Bilgileri düzenleyip tekrar gönderin": "Edit information and resubmit",
        "Onay için gönderin": "Submit for approval",
        "Tekrar incelemeye gönder": "Submit for review again",
        "İncelemeye gönder": "Submit for review",
        "Başvurunuz inceleniyor. Onaylandıktan sonra ilan açabileceksiniz.": "Your application is under review. You can open a listing after approval.",
        "İstenen belgeleri güncelledikten sonra başvurunuzu yeniden incelemeye gönderin.": "Submit your application for review again after updating the requested documents.",
        "Gerekli düzeltmeleri yaptıktan sonra başvurunuzu yeniden gönderebilirsiniz.": "You can resubmit your application after making the necessary corrections.",
        "Oturum bilgisi bulunamadı.": "Session information not found.",
        "Profil bilgileri": "Profile information",
        "İşletme ve profesyonel bilgiler": "Business and professional information",
        "Şirket/şahıs, kategori, deneyim, vergi no, sertifika": "Company/individual, category, experience, tax no, certificate",
        "Çalışma detayları": "Work details",
        "Şehir, günler, saatler, fiyat": "City, days, hours, price",
        "Banka bilgileri": "Bank details",
        "IBAN, hesap sahibi": "IBAN, account holder",
        "Adres ve Hakkında": "Address and About",
        "Adres, kısa tanıtım": "Address, brief introduction",
        "Kimlik doğrulama": "Identity verification",
        "Kimlik belgesi ön ve arka yüz": "ID card front and back",
        "Önceki işlerinizden fotoğraflar": "Photos from your previous works",
        "yıl deneyim": "years of experience",
        "Adres": "Address",
        "Çalışma adresiniz veya hizmet verdiğiniz bölge": "Your work address or service area",
        "Kendinizi ve hizmetlerinizi kısaca tanıtın": "Briefly introduce yourself and your services",
        "Kaydet": "Save",
        "Kimlik belgenizin ön ve arka yüzünün net fotoğraflarını yükleyin.": "Upload clear photos of the front and back of your ID card.",
        
        // Expert Listings Page
        "İlanlar yükleniyor...": "Loading listings...",
        "İlanlar yüklenemedi": "Could not load listings",
        "İlanı sil": "Delete listing",
        "Sil": "Delete",
        " ilanı silinecek. Bu işlem geri alınamaz.": " listing will be deleted. This action cannot be undone.",
        "Yayındaki ilanlar": "Active listings",
        " ilan": " listings",
        "Henüz ilanınız yok": "You don't have any listings yet",
        "Ana uzman ekranındaki + butonu ile yeni ilan açabilir,\nmüşterilere hizmetlerinizi sunabilirsiniz.": "You can open a new listing with the + button on the main expert screen,\nand offer your services to customers.",
        "İlanı Düzenle": "Edit Listing",
        "İlan görseli": "Listing image",
        "İlan Görselini Değiştir": "Change Listing Image",
        "Yeni görsel kaydetme sırasında yüklenecek.": "New image will be uploaded during save.",
        "Temel bilgiler": "Basic info",
        "İlan başlığı": "Listing title",
        "Başlık": "Title",
        "Fiyat ve süre": "Price and duration",
        "Süre": "Duration",
        "Fiyat (₺)": "Price (₺)",
        "Fiyat": "Price",
        "Konum ve açıklama": "Location and description",
        "Açıklama": "Description",
        "İlan görseli yok": "No listing image",
        "Geçerli bir fiyat girin.": "Please enter a valid price.",
        "Seçilen görsel okunamadı.": "The selected image could not be read.",
        "30 dk": "30 min",
        "1 saat": "1 hour",
        "2 saat": "2 hours",
        "Yarım gün": "Half day",
        "Tam gün": "Full day",
        "Proje bazlı": "Project based",
        
        // Messages Page
        "Henüz Mesajınız Yok": "No Messages Yet",
        "Ustalar veya müşterilerle yaptığınız tüm yazışmalar burada güvenle saklanır.": "All your conversations with experts or customers are safely stored here.",
        "Dün": "Yesterday",
        
        // Provider Dashboard
        "Dashboard yükleniyor...": "Loading dashboard...",
        "Bugünkü Randevu": "Today's Appointments",
        "Bekleyen Talep": "Pending Requests",
        "Yaklaşan Randevu": "Upcoming Appointments",
        "Tamamlanan İş": "Completed Jobs",
        "Usta Paneli": "Expert Dashboard",
        "Çalışma Durumu": "Working Status",
        "Yeni İşlere Açıksınız": "Open to New Jobs",
        "Müsait Değilsiniz": "Not Available",
        "Bekleyenler": "Pending",
        "Yeni": "New",
        "Bugünün Randevuları": "Today's Appointments",
        "Bugün için planlanmış bir randevunuz bulunmamaktadır.": "You have no appointments scheduled for today.",
        "İş İstatistikleri": "Job Statistics",
        "Son 6 Ay Tamamlanan İşler": "Completed Jobs in Last 6 Months",
        "Henüz tamamlanan iş yok": "No completed jobs yet",
        "Son altı aya ait tamamlanan iş verisi bulunmuyor.": "No completed job data for the last six months.",
        "Ay": "Month",
        "Tamamlanan Hizmet Dağılımı": "Completed Services Distribution",
        "Hizmet verisi bulunmuyor": "No service data",
        "Tamamlanan işler oluştuğunda hizmet dağılımı burada gösterilecek.": "Service distribution will be shown here when completed jobs occur.",
        
        // Finance View
        "Finansal Yönetim": "Financial Management",
        "Para Çek": "Withdraw",
        "Toplam Bakiye": "Total Balance",
        "Çekilebilir Bakiye": "Withdrawable Balance",
        "Banka Hesabına Aktar": "Transfer to Bank Account",
        "Kazanç Geçmişi": "Earnings History",
        "Para Çekme Talepleri": "Withdrawal Requests",
        "Henüz para çekme talebiniz bulunmamaktadır.": "You have no withdrawal requests yet.",
        "Faturalar ve Vergiler": "Invoices and Taxes",
        "Komisyon Faturası": "Commission Invoice",
        "Görüntüle": "View",
        "Çekim Talebi Oluştur": "Create Withdrawal Request",
        "Çekilebilir Tutar": "Withdrawable Amount",
        "Çekilecek Tutar (₺)": "Amount to Withdraw (₺)",
        "Tutar": "Amount",
        "Banka Seçimi": "Bank Selection",
        "Banka": "Bank",
        "IBAN Numarası": "IBAN Number",
        "Talep Gönder": "Submit Request",
        "UzmanaGel Dijital Fatura": "UzmanaGel Digital Invoice",
        "Fatura Dönemi:": "Invoice Period:",
        "Fatura Numarası:": "Invoice Number:",
        "Hizmet Komisyon Bedeli:": "Service Commission Fee:",
        "Bu fatura elektronik imza ile imzalanmıştır. Maliye Bakanlığı standartlarına uygundur.": "This invoice is signed with an electronic signature. It complies with Ministry of Finance standards.",
        "Paylaş veya İndir": "Share or Download",
        "Fatura Detayı": "Invoice Detail",
        
        // Schedule View
        "Çalışma Takvimi": "Work Calendar",
        "Toplu Müsaitlik Düzenle": "Batch Availability Edit",
        "Çalışma Gün ve Saatleri": "Working Days and Hours",
        "Müsait": "Available",
        "Kısmi Dolu": "Partially Booked",
        "Dolu / Kapalı": "Booked / Closed",
        "Planlanmamış": "Unscheduled",
        "Bugün Hizmete Açık": "Open for Service Today",
        "Saat Dilimleri": "Time Slots",
        "Dolu (Randevu Alındı)": "Booked (Appointment Scheduled)",
        "Günün Rezervasyonları": "Today's Reservations",
        "Müsaitlik Girilmemiş": "Availability Not Entered",
        "Bu gün için çalışma planı bulunmamaktadır.": "There is no work plan for today.",
        "Gün Detayı": "Day Detail",
        "Başlangıç Tarihi": "Start Date",
        "Bitiş Tarihi": "End Date",
        "Hizmete Açık (Müsait)": "Open for Service (Available)",
        "Müsaitliği Uygula": "Apply Availability",
        "Toplu Düzenleme": "Batch Editing",
        "Standart Çalışma Saatleri": "Standard Working Hours",
        "ile": "to",
        "arası": "between",
        "Çalışılan Günler": "Working Days",
        "Varsayılan Ayarları Kaydet": "Save Default Settings",
        "Çalışma Ayarları": "Working Settings",
        "Pzt": "Mon",
        "Sal": "Tue",
        "Çar": "Wed",
        "Per": "Thu",
        "Cum": "Fri",
        "Cmt": "Sat",
        "Paz": "Sun"
    ]
}

extension String {
    var localized: String {
        return LanguageManager.shared.translate(self)
    }
    
    func decodeBase64ToImage() -> UIImage? {
        var cleanString = self
        if cleanString.hasPrefix("data:image") {
            let components = cleanString.components(separatedBy: ",")
            if components.count > 1 {
                cleanString = components[1]
            }
        }
        guard let data = Data(base64Encoded: cleanString) else { return nil }
        return UIImage(data: data)
    }
}
